### ISSUE TITLE
convert-array solution is wrong

### ISSUE THREAD

**Issue by adrianN** [mre/the-coding-interview#12]
This solution is not in place:

https://github.com/mre/the-coding-interview/blob/d32fb46c10912b0336d5b788f074e5682af6c42a/problems/convert-array/convert-array.py

**Comment by mre** [comment]
Oops, thanks for noticing @adrianN. I'll happily accept pull requests with a proper solution. If you like, you can give it a shot. 😃

**Comment by oniani** [comment]
It was also not an `in-place` conversion.
It's fixed now.
